app:
  name: users-service
  environment: staging
  group: backend
  container:
    image:
      repository: registry.digitalocean.com/akatsuki/users-service
      tag: latest
    imagePullSecrets:
      - name: akatsuki
    port: 80
